const gastos_plan = {
  1: {
    id: "PASAJE_VALDI",
    nombre: "Pasaje Valdiviezo",
    unidad: "u",
    precio_relativo: 1,
    precio_plan_mensual: 80,
    mejor_lugar_compra: "NA",
    duracion_estimada: "1 Dia",
    tipo_gasto: "servicio",
    cantidad_plan: "NA",
    img: "pasaje_valdi.png",
    subcategoria: "pasajes",
    categoria: "otros_gastos",
    planificado: "X",
  },
  2: {
    id: "PASAJE_SEIDOR",
    nombre: "Pasaje Seidor",
    unidad: "u",
    precio_relativo: 15,
    precio_plan_mensual: 50,
    mejor_lugar_compra: "NA",
    duracion_estimada: "1 Dia",
    tipo_gasto: "servicio",
    cantidad_plan: "NA",
    img: "pasaje_seidor.png",
    subcategoria: "pasajesss",
    categoria: "otros_gastos",
    planificado: "",
  },
  3: {
    id: "CAFE",
    nombre: "Café",
    unidad: "u",
    precio_relativo: 10.5,
    precio_plan_mensual: 42,
    mejor_lugar_compra: "Tienda frentea al condominio",
    duracion_estimada: "2 semanas por bolsa",
    tipo_gasto: "semanal",
    cantidad_plan: 4,
    img: "img_cafe.png",
    subcategoria: "cafe",
    categoria: "cafe",
    planificado: "X",
  },
  4: {
    id: "AZUCAR",
    nombre: "Azucar",
    unidad: "Kg",
    precio_relativo: 4,
    precio_plan_mensual: 8,
    mejor_lugar_compra: "Tienda frentea al condominio",
    duracion_estimada: "2 semanas por Kilo",
    tipo_gasto: "semanal",
    cantidad_plan: 2,
    img: "azucar.png",
    subcategoria: "azucar",
    categoria: "abarrotes",
    planificado: "X",
  },
  5: {
    id: "HIGADO",
    nombre: "Higado",
    unidad: "Kg",
    precio_relativo: 6.5,
    precio_plan_mensual: 39,
    mejor_lugar_compra: "Mercado valdiviezo",
    duracion_estimada: "1 semana por 1 kilo",
    tipo_gasto: "semanal",
    cantidad_plan: 6,
    img: "higado.png",
    subcategoria: "higado",
    categoria: "higado",
    planificado: "X",
  },
  6: {
    id: "HUEVO",
    nombre: "Huevos",
    unidad: "Kg",
    precio_relativo: 1,
    precio_plan_mensual: 48,
    mejor_lugar_compra: "Mercado valdiviezo",
    duracion_estimada: "1 semana por 2kg",
    tipo_gasto: "semanal",
    cantidad_plan: 6,
    img: "huevos.png",
    subcategoria: "huevos",
    categoria: "abarrotes",
    planificado: "X",
  },
  7: {
    id: "SHAMPOO",
    nombre: "Shampoo",
    unidad: "u",
    precio_relativo: 17.5,
    precio_plan_mensual: 17.5,
    mejor_lugar_compra: "Minimarket valdiviezo",
    duracion_estimada: "2 Meses por botella",
    tipo_gasto: "semanal",
    cantidad_plan: 1,
    img: "shampoo.png",
    subcategoria: "shampoo",
    categoria: "abarrotes",
    planificado: "X",
  },
  8: {
    id: "COLINOS",
    nombre: "Colinos",
    unidad: "u",
    precio_relativo: 18.75,
    precio_plan_mensual: 18.75,
    mejor_lugar_compra: "Tottus",
    duracion_estimada: "1 Mes por pack de 2",
    tipo_gasto: "semanal",
    cantidad_plan: 1,
    img: "colinos.png",
    subcategoria: "Colinos",
    categoria: "abarrotes",
    planificado: "X",
  },
  9: {
    id: "PAPEL_HIGIENICO",
    nombre: "Papel Higiénico",
    unidad: "u",
    precio_relativo: 44.9,
    precio_plan_mensual: 44.9,
    mejor_lugar_compra: "Maestro",
    duracion_estimada: "2 Meses por Bolsa (16 unidades)",
    tipo_gasto: "semanal",
    cantidad_plan: 1,
    img: "papel_higienico.png",
    subcategoria: "papel_higienico",
    categoria: "abarrotes",
    planificado: "X",
  },
  10: {
    id: "LEJIA",
    nombre: "Lejía",
    unidad: "u",
    precio_relativo: 10.9,
    precio_plan_mensual: 10.9,
    mejor_lugar_compra: "Tottus",
    duracion_estimada: "1 Mes por botella 5 Litros",
    tipo_gasto: "semanal",
    cantidad_plan: 1,
    img: "lejia.png",
    subcategoria: "lejia",
    categoria: "abarrotes",
    planificado: "",
  },
  11: {
    id: "ENJUAGUE_BUCAL",
    nombre: "Enjuague bucal",
    unidad: "u",
    precio_relativo: 23.9,
    precio_plan_mensual: 23.9,
    mejor_lugar_compra: "Tottus",
    duracion_estimada: "1 Mes por botella 500 ml",
    tipo_gasto: "semanal",
    cantidad_plan: 1,
    img: "enjuague_bucal.png",
    subcategoria: "enjuague_bucal",
    categoria: "abarrotes",
    planificado: "X",
  },
  12: {
    id: "DETERGENTE",
    nombre: "Detergente",
    unidad: "u",
    precio_relativo: 40.6,
    precio_plan_mensual: 40.6,
    mejor_lugar_compra: "Tottus",
    duracion_estimada: "2 Mes por 4kg Opal",
    tipo_gasto: "semanal",
    cantidad_plan: 1,
    img: "detergente.png",
    subcategoria: "detergente",
    categoria: "abarrotes",
    planificado: "",
  },
  13: {
    id: "ALMUERZO",
    nombre: "Almuerzo",
    unidad: "u",
    precio_relativo: 12,
    precio_plan_mensual: 360,
    mejor_lugar_compra: "Casa mamá",
    duracion_estimada: "Mensual",
    tipo_gasto: "servicio",
    cantidad_plan: 30,
    img: "almuerzo.png",
    subcategoria: "almuerzo",
    categoria: "almuerzo",
    planificado: "X",
  },
  14: {
    id: "LUZ",
    nombre: "Luz del sur",
    unidad: "u",
    precio_relativo: 80,
    precio_plan_mensual: 80,
    mejor_lugar_compra: "Casa mamá",
    duracion_estimada: "Mensual",
    tipo_gasto: "servicio",
    cantidad_plan: 1,
    img: "luz.png",
    subcategoria: "luz_sur",
    categoria: "servicios",
    planificado: "X",
  },
  15: {
    id: "INTERNET",
    nombre: "Internet claro",
    unidad: "u",
    precio_relativo: 39,
    precio_plan_mensual: 39,
    mejor_lugar_compra: "Casa mamá",
    duracion_estimada: "Mensual",
    tipo_gasto: "servicio",
    cantidad_plan: 1,
    img: "internet.png",
    subcategoria: "internet",
    categoria: "servicios",
    planificado: "X",
  },
  16: {
    id: "MANTENIMIENTO",
    nombre: "Mantenimiento",
    unidad: "u",
    precio_relativo: 150,
    precio_plan_mensual: 150,
    mejor_lugar_compra: "Casa",
    duracion_estimada: "Mensual",
    tipo_gasto: "servicio",
    cantidad_plan: 1,
    img: "mantenimiento.png",
    subcategoria: "mantenimiento",
    categoria: "servicios",
    planificado: "X",
  },
  17: {
    id: "PLAN_CELULAR",
    nombre: "Plan celular",
    unidad: "u",
    precio_relativo: 25,
    precio_plan_mensual: 25,
    mejor_lugar_compra: "Casa",
    duracion_estimada: "Mensual",
    tipo_gasto: "servicio",
    cantidad_plan: 1,
    img: "entel.png",
    subcategoria: "celular",
    categoria: "servicios",
    planificado: "X",
  },
  18: {
    id: "GAS",
    nombre: "Gas calidda",
    unidad: "u",
    precio_relativo: 13.8,
    precio_plan_mensual: 13.8,
    mejor_lugar_compra: "Casa",
    duracion_estimada: "Mensual",
    tipo_gasto: "servicio",
    cantidad_plan: 1,
    img: "gas.png",
    subcategoria: "gas",
    categoria: "servicios",
    planificado: "X",
  },
  19: {
    id: "OTROS",
    nombre: "Otros",
    unidad: "u",
    precio_relativo: 0,
    precio_plan_mensual: 200,
    mejor_lugar_compra: "",
    duracion_estimada: "",
    tipo_gasto: "extra",
    cantidad_plan: 1,
    img: "otros.png",
    subcategoria: "otros_gastos",
    categoria: "otros_gastos",
    planificado: "X",
  },
  20: {
    id: "ARROZ",
    nombre: "Arroz",
    unidad: "kg",
    precio_relativo: 4.5,
    precio_plan_mensual: 14.9,
    mejor_lugar_compra: "",
    duracion_estimada: "",
    tipo_gasto: "extra",
    cantidad_plan: 5,
    img: "arroz.png",
    subcategoria: "arroz",
    categoria: "perros",
    planificado: "X",
  },

  21: {
    id: "DULCES",
    nombre: "Dulces",
    unidad: "u",
    precio_relativo: 0,
    precio_plan_mensual: 50,
    mejor_lugar_compra: "",
    duracion_estimada: "",
    tipo_gasto: "extra",
    cantidad_plan: 1,
    img: "dulces.png",
    subcategoria: "dulces",
    categoria: "otros_gastos",
    planificado: "X",
  },
  22: {
    id: "PATES",
    nombre: "Pates",
    unidad: "u",
    precio_relativo: 0,
    precio_plan_mensual: 45,
    mejor_lugar_compra: "",
    duracion_estimada: "",
    tipo_gasto: "extra",
    cantidad_plan: 1,
    img: "pates.png",
    subcategoria: "pates",
    categoria: "perros",
    planificado: "X",
  },
  23: {
    id: "POLLO",
    nombre: "Pollo",
    unidad: "u",
    precio_relativo: 0,
    precio_plan_mensual: 28,
    mejor_lugar_compra: "",
    duracion_estimada: "",
    tipo_gasto: "extra",
    cantidad_plan: 1,
    img: "pollo.png",
    subcategoria: "pollo",
    categoria: "perros",
    planificado: "X",
  },
  24: {
    id: "DOGSHOW",
    nombre: "Dog show",
    unidad: "u",
    precio_relativo: 0,
    precio_plan_mensual: 91,
    mejor_lugar_compra: "",
    duracion_estimada: "",
    tipo_gasto: "extra",
    cantidad_plan: 1,
    img: "dogshow.png",
    subcategoria: "dogshow",
    categoria: "perros",
    planificado: "",
  },
  25: {
    id: "HBO",
    nombre: "HBO GO",
    unidad: "u",
    precio_relativo: 30,
    precio_plan_mensual: 30,
    mejor_lugar_compra: "Casa",
    duracion_estimada: "Mensual",
    tipo_gasto: "servicio",
    cantidad_plan: 1,
    img: "DGO.png",
    subcategoria: "hbogo",
    categoria: "servicios",
    planificado: "X",
  },
  26: {
    id: "ACONDICIONADOR",
    nombre: "Acondicionador",
    unidad: "u",
    precio_relativo: 30,
    precio_plan_mensual: 30,
    mejor_lugar_compra: "Minimarket valdiviezo",
    duracion_estimada: "2 Meses por botella",
    tipo_gasto: "semanal",
    cantidad_plan: 1,
    img: "acondicionador.png",
    subcategoria: "Acondicionador",
    categoria: "abarrotes",
    planificado: "X",
  },
  27: {
    id: "JABON",
    nombre: "Jabón",
    unidad: "u",
    precio_relativo: 8,
    precio_plan_mensual: 8,
    mejor_lugar_compra: "Minimarket valdiviezo",
    duracion_estimada: "2 Meses por botella",
    tipo_gasto: "semanal",
    cantidad_plan: 1,
    img: "jabon.png",
    subcategoria: "jabon",
    categoria: "abarrotes",
    planificado: "X",
  },
  28: {
    id: "ACEITE",
    nombre: "Aceite",
    unidad: "u",
    precio_relativo: 10,
    precio_plan_mensual: 10,
    mejor_lugar_compra: "Minimarket valdiviezo",
    duracion_estimada: "2 Meses por botella",
    tipo_gasto: "semanal",
    cantidad_plan: 1,
    img: "aceite.png",
    subcategoria: "Aceite",
    categoria: "abarrotes",
    planificado: "X",
  },
};
